#on: push
#on:
 #schedule:
   # - cron: "7 9 * * *" # time is in utc, so Berlin -2h

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: insightsengineering/pip-action@v2
        with:
          packages: |
              requests
              pandas
              datawrapper
              bs4
               
      - name: execute py script
        run: python ./UNCHR-Arrivals-Europe.py
